<%
  # Update these properties as required
  deployment_name  = 'graphite-bosh-lite'
  director_uuid    = 'bf3dbdbd-50df-4588-8056-b57889d5ddca'
  stemcell_name    = 'bosh-warden-boshlite-ubuntu-trusty-go_agent'
  stemcell_version = 'latest'
%>

name: <%= deployment_name %>
director_uuid: <%= director_uuid %>

releases:
- name: graphite
  version: latest

jobs:
- name: graphite
  templates:
  - name: carbon
    release: graphite
  - name: graphite-web
    release: graphite
  - name: statsd
    release: graphite
  instances: 1
  resource_pool: small_z1
  persistent_disk: 2048
  networks:
  - name: default
    static_ips:
    - 10.244.2.2

properties:
  carbon:
    storage_schemas:
      - name: "my_storage_schema"
        pattern: "^my\\.metrics\\.*" # NB: Note that double escapes - this will evaluate to "my\.metrics\.*"
        retentions: "60s:1d"
      - name: "my_storage_schema_2"
        pattern: "metrics$"
        retentions: "15s:7d,1m:21d,15m:5y"
  graphite-web:
    time_zone: Europe/London
    httpd:
      port: 80
    wsgi:
      inactivity-timeout: 60

meta:
  environment: <%= deployment_name %>
  stemcell:
    name: <%= stemcell_name %>
    version: <%= stemcell_version %>

resource_pools:
- cloud_properties:
    name: random
  name: small_z1
  network: default
  size: 1
  stemcell:
    name: <%= stemcell_name %>
    version: <%= stemcell_version %>

compilation:
  cloud_properties:
    name: random
  network: default
  reuse_compilation_vms: true
  workers: 4

update:
  canaries: 1
  canary_watch_time: 1000-30000
  max_in_flight: 50
  serial: false
  update_watch_time: 1000-30000

networks:
- name: default
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.2.0/30
    reserved:
    - 10.244.2.1
    static:
    - 10.244.2.2
  - cloud_properties:
      name: random
    range: 10.244.2.4/30
    reserved:
    - 10.244.2.5
    static:
    - 10.244.2.6
  - cloud_properties:
      name: random
    range: 10.244.2.8/30
    reserved:
    - 10.244.2.9
    static:
    - 10.244.2.10
  - cloud_properties:
      name: random
    range: 10.244.2.12/30
    reserved:
    - 10.244.2.13
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.16/30
    reserved:
    - 10.244.2.17
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.20/30
    reserved:
    - 10.244.2.21
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.24/30
    reserved:
    - 10.244.2.25
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.28/30
    reserved:
    - 10.244.2.29
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.32/30
    reserved:
    - 10.244.2.33
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.36/30
    reserved:
    - 10.244.2.37
    static: []
